RealStateGestion/Controllers/PlanesController.cs
using Microsoft.AspNetCore.Mvc;
using RealStateGestion.Datos.Center;
using RealStateGestion.Models;
using System.Linq;

namespace RealStateGestion.Controllers
{
    public class PlanesController : Controller
    {

        //Traer 
        PlanesCenter _PlanesData = new PlanesCenter();


        //Método para el mostrado del formulario
        [HttpGet]
        public IActionResult Planes()
        {
            //Creando varaiable para almacenar valores en el modelo
            var planesModel = new PlanesModel();

            //Llamando al método Listar, el cual trae los datos principales de los planes
            var oListaPlanes = _PlanesData.Listar();

            //Llamando al método Listar2, el cual trae las caracteristicas seleccionadas de los planes
            var oListaPlanesCaract = _PlanesData.Listar2();

            //Almacenando dentro de las listas y poder obtenerlas en el front
            //Planes datos generales
            planesModel.planesG = oListaPlanes;
            //Planes características
            planesModel.planesCaract = oListaPlanesCaract;

            //Envío de datos para la visualización de la alerta

            ViewBag.mssg = TempData["mssg"] as string;
            ViewBag.mssgE = TempData["mssgE"] as string;
            return View(planesModel);
        }

        //Para la edición de planes 
        public IActionResult planesAct(int plan)
        {
            var planesModel = new PlanesModel();

            //Enviando el ID del plan al modelo
            planesModel.IDPlan = plan;

            //Para obtener los datos principales del Plan 
            var oListaPlanesG = _PlanesData.Listar();
            //Almacenando dentro de la lista declarada en el modelo
            planesModel.planesG = oListaPlanesG;

            //Esta lista contiene todas las caracteristicas para los planes
            //Llamando al método ListarCaractT, el cual trae todas las características a seleccionar de los planes
            var oListaPlanesCaractG = _PlanesData.ListarCaractG();
            //Almacenando dentro de la lista declarada en el modelo
            planesModel.planesCaractG = oListaPlanesCaractG;

            //Está lista contiene las caracteristicas particulares de cada plan
            var oListaCaractInd = _PlanesData.CaractSelect(plan);
            //Almacenando en la lista declara en el modelo
            planesModel.planesCaractIndv = oListaCaractInd;

            return View(planesModel);
        }
    }
}

RealStateGestion/Views/Planes/Planes.cshtml
@model PlanesModel

<link rel="stylesheet" href="~/css/config_planes_style.css" asp-append-version="true" />

<form action="">
    <div class="carousel-inner">
        <div class="row  my-5 d-flex justify-content-center">

            <div class="col-lg-3">
                <div class="caja-3 mx-auto shadow-lg mb-3 zoom">
                    @foreach (var item in Model.planesG)
                    {
                        @if (@item.IDplanEcomm == 1)
                        {

                            <div class="card-center-1">

                                <div class="title-cards-1 col-5">
                                    <h5>@item.nombrePlan</h5>
                                </div>

                                <div class="prize-house col-5  d-inline-flex my-2">
                                    <img src="~/img/Bronce.png" alt="" class=" casa-3">
                                    <div class="my-3 text-light col-lg-2 col-3  ms-2  d-flex ">
                                        @{
                                            double precio = Convert.ToDouble(@item.precioTotal);
                                            var precioTotal = precio.ToString("N0", new System.Globalization.CultureInfo("en-US"));
                                        }
                                        <h1 class="justify-content-center fw-bold ">$@precioTotal</h1>
                                    </div>

                                </div>

                            </div>
                            <div class="body-card  d-flex">
                                <div class="col-11 mx-auto  text-dark">
                                    <h6 class="letter_space ">Hasta @item.propiedades propiedades</h6>
                                    @{
                                        var x = 1;
                                    }
                                    @foreach (var itemcaract1 in Model.planesCaract)
                                    {
                                        x = x + 1;
                                        @if (@itemcaract1.IDPlan == 1)
                                        {
                                            <h6 class="letter_size ">@itemcaract1.caractPlanEcomm</h6>
                                        }
                                    }
                                </div>
                            </div>

                            <div class="body-card">
                                <div class="col-5 mx-auto text-light  justify-content-center d-flex  my-2 text-center">
                                    <a href="edit_config_planes.html">
                                       <a class="btn btn_s ps-3 my-4" asp-controller="Planes" asp-action="planesAct" asp-route-plan="@item.IDplanEcomm">
                                        <i class="fa-solid fa-pencil fa-1x d-flex me-1"></i>
                                    </a>
                                    </a>

                                </div>
                            </div>
                        }
                    }
                </div>

                <ul class='circles'>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>

            </div>
            <div class="col-lg-3">
                <div class="caja-3 mx-auto shadow-lg mb-3 zoom">

                    @foreach (var item2 in Model.planesG)
                    {
                        @if (@item2.IDplanEcomm == 2)
                        {
                            <div class="card-center-2">

                                <div class="title-cards-2 col-5">
                                    <h5>@item2.nombrePlan</h5>
                                </div>

                                <div class="prize-house col-5  d-inline-flex my-2">
                                    <img src="~/img/plata.png" alt="" class=" casa-3">
                                    <div class="my-3 text-light col-lg-2 col-3  ms-2  d-flex ">
                                        @{
                                            double precio = Convert.ToDouble(@item2.precioTotal);
                                            var precioTotal2 = precio.ToString("N0", new System.Globalization.CultureInfo("en-US"));
                                        }
                                        <h1 class="  justify-content-center fw-bold ">$@precioTotal2</h1>
                                    </div>

                                </div>

                            </div>

                            <div class="body-card  d-flex">
                                <div class="col-11 mx-auto  text-dark">
                                    <h6 class="letter_space">Hasta @item2.propiedades propiedades</h6>
                                    @{
                                        var x = 1;
                                    }
                                    @foreach (var itemcaract1 in Model.planesCaract)
                                    {
                                        x = x + 1;
                                        @if (@itemcaract1.IDPlan == 2)
                                        {
                                            <h6 class="letter_size ">@itemcaract1.caractPlanEcomm</h6>
                                        }
                                    }
                                </div>
                            </div>
                            <div class="body-card">
                                <div class="col-5 mx-auto   text-light  justify-content-center  text-center">
                                    <a class="btn btn_s ps-3 my-4" asp-controller="Planes" asp-action="planesAct" asp-route-plan="@item2.IDplanEcomm">
                                        <i class="fa-solid fa-pencil fa-1x d-flex me-1"></i>
                                    </a>
                                                                     
                                </div>
                            </div>
                        }
                    }
                </div>


            </div>

            <div class="col-lg-3">
                <div class="caja-3 mx-auto shadow-lg mb-3 zoom">
                    @foreach (var item3 in Model.planesG)
                    {
                        @if (@item3.IDplanEcomm == 3)
                        {
                            <div class="card-center-3">

                                <div class="title-cards-1 col-5">
                                    <h5>@item3.nombrePlan</h5>
                                </div>

                                <div class="prize-house col-5  d-inline-flex my-2">
                                    <img src="~/img/oro.png" alt="" class=" casa-3">
                                    <div class="my-3 text-light col-lg-2 col-3  ms-2  d-flex ">
                                        @{
                                            double precio = Convert.ToDouble(@item3.precioTotal);
                                            var precioTotal3 = precio.ToString("N0", new System.Globalization.CultureInfo("en-US"));
                                        }
                                        <h1 class="  justify-content-center fw-bold ">$@precioTotal3</h1>
                                    </div>

                                </div>
                            </div>

                            <div class="body-card  d-flex">
                                <div class="col-11 mx-auto  text-dark">
                                    <h6 class="letter_space">Hasta @item3.propiedades propiedades</h6>
                                    @{
                                        var x = 1;
                                    }
                                    @foreach (var itemcaract3 in Model.planesCaract)
                                    {

                                        x = x + 1;
                                        @if (@itemcaract3.IDPlan == 3)
                                        {
                                            <h6 class="letter_size ">@itemcaract3.caractPlanEcomm</h6>
                                        }
                                    }
                                </div>
                            </div>

                            <div class="body-card  d-flex">
                                <div class="col-5 mx-auto text-light  justify-content-center  text-center">
                                     <a class="btn btn_s ps-3 my-4" asp-controller="Planes" asp-action="planesAct" asp-route-plan="@item3.IDplanEcomm">
                                        <i class="fa-solid fa-pencil fa-1x d-flex me-1"></i>
                                    </a>



                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</form>

RealStateGestion/Views/Planes/planesAct.cshtml
@model PlanesModel;

<link rel="stylesheet" href="~/css/styles_edit_config_planes.css" asp-append-version="true" />

<ul class="circles">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
</ul>

<br />
<div class="container-fluid">
    <div class="row">
        <div class="col">

            <form action="#" class="form">



                <label for=""><h5>Configuración de planes</h5></label>
                <div class="input-group justify-content-between  d-lg-inline-flex mt-2 mb-3">
                    <div class=" d-lg-inline-block col-lg-4 mt-lg-3 mt-ms-4 ms-5 ">
                        <label for="t_propiedad" class="text-start fw-bold color_letter">Tipo de propiedad</label>
                  
                        @Html.DropDownListFor(model => model.IDPlan, new SelectList(Model.planesG,"IDplanEcomm","nombrePlan"), "-- Selecciona --",new {@class="border-labels rounded text-center mt-lg-2"})

                    </div>

                    <div class=" d-lg-inline-block mt-lg-2 mb-3 ps-1 ">
                        <label for="nombre" class="text-start mb-3 fw-bold color_letter size-text">Nombre</label>
                        <input type="text" name="nombre" class="mt-lg-2" />
                    </div>
                    <div class=" d-lg-inline-block">
                        <label for="precio" class="text-start  fw-bold color_letter size-text">Precio</label>
                        <input type="text" id="value1" readonly class="value_s mt-lg-2">
                    </div>
                </div>
                <div class="input-group justify-content-start  d-lg-inline-flex mt-2 mb-3">
                    <div class=" d-lg-inline-flex  mb-3 ps-1 ">
                        <label for="nombre" class="text-start  fw-bold color_letter size-text">¿Hasta cuántas propiedades?</label>
                        <input type="number" name="propiedades" class="" />
                    </div>
                </div>
                <hr>
                <label for=""><h5>Caracteristicas</h5></label>



                <div class="input-group d-lg-inline-flex justify-content-between mt-lg-3 align-content-between ">



                    <div class="table-wrapper-scroll-y my-custom-scrollbar table-responsive col-12">
                        <table class="table table-hover border">
                            <thead>
                                <tr>
                                    <th scope="col">Selecciona</th>
                                    <th scope="col">#</th>
                                    <th scope="col">Caracteristicas</th>
                                    <th scope="col">Principales</th>
                                </tr>
                            </thead>
                            <tbody>

                                @for (var i = 0; i < Model.planesCaractG.Count; ++i)
                                {
                                    bool seleccionada=false;

                                    foreach (var ite in Model.planesCaractIndv)
                                    {
                                        if (ite.IDcatCaractPlanEcommRel == Model.planesCaractG[i].IDcatPlan)
                                        {
                                            seleccionada = true;
                                        }
                                    }
                                    <tr>
                                        <th scope="row">
                                            @if (seleccionada)
                                            {
                                                @Html.CheckBoxFor(model => model.planesCaractG[i].isSelected, new {@class = "form-check-input mt-0 border-check", @id=Model.IDcatPlan})
                                            }
                                            else

                                            {
                                                @Html.CheckBoxFor(model => model.planesCaractG[i].isnotSelected, new {@class = "form-check-input mt-0 border-check"})
                                            }
                                        </th>
                                         
                                        <td>@Html.DisplayFor(model => model.planesCaractG[i].IDcatPlan)</td>
                                        <td>@Html.DisplayFor(model => model.planesCaractG[i].caractPlanEcomm)</td>
                                        <td><input class="form-check-input mt-0 border-check" type="checkbox" value="" aria-label="Checkbox for following text input"></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

                <br>
                <br>
                <div class="input-group d-lg-inline-flex justify-content-between mb-5 align-content-between">
                    <div class="">
                        <label for="">Precio</label>
                        <input type="number" name="precio" id="num">
                    </div>
                    <div class="">
                        <label for="">Promoción %</label>
                        <input type="number" name="promocion" id="percent">
                    </div>
                    <div class="mt-lg-4">
                        <input type="button" onclick="percentage_1()" value="Aplicar" class="btn btn-primary border-bottom-0"></input>
                    </div>
                    <div class="">
                        <label for="">Inicio</label>
                        <input type="date" name="" id="">
                    </div>
                    <div class=" me-2">
                        <label for="">Termina</label>
                        <input type="date" name="" id="">
                    </div>

                </div>

                <div class="justify-content-end d-flex">
                    <button type="submit" class=" btn btn-orange circle-btn   ml-auto"><i class="fa-solid fa-check text-light"></i></button>
                </div>

            </form>
        </div>

    </div>
</div>