EcommerceRealCVO/Controllers/CuentasController.cs
using EcommerceRealCVO.Datos.Center;
using EcommerceRealCVO.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Text.Json;

namespace EcommerceRealCVO.Controllers
{
    public class CuentasController : Controller
    {
        //Inyeccion de dependencias 
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IEmailSender _emailSender;

        //CONTACTO 
        ContactoCenter _ContactoData = new ContactoCenter();

        //INTEGRACION
        IntegracionCenter _IntegracionData = new IntegracionCenter();

        //Creación de constructor
        public CuentasController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
        }

        OnboardingBroker _OnboardingBroker = new OnboardingBroker();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AlertaProvisional()
        {
            ViewBag.mssg = TempData["mssg"] as string;
            ViewBag.mssgE = TempData["mssgE"] as string;
            return View();
        }


        [HttpGet] //Método para el mostrado del formulario
        public async Task<IActionResult> Registro(string? returnurl = null)
        {

            ViewData["ReturnUrl"] = returnurl;

            RegistroVModel registroVM = new RegistroVModel();

            return View(registroVM);
        }

       // ---------------------------

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> QuieroSaberMas(PlanesModel planesVMODEL)
        {

            if (planesVMODEL.NombreQS != null)
            {
                var oContacto = new ContactoModel();
                //Concato cuando es LB
                oContacto.Nombre = planesVMODEL.NombreQS;
                oContacto.APaterno = planesVMODEL.APaternoQS;
                oContacto.AMaterno = planesVMODEL.AMaternoQS;
                oContacto.Mensaje = planesVMODEL.MensajeQS;
                oContacto.Telefono = planesVMODEL.TelefonoQS;
                oContacto.FechaContacto = planesVMODEL.FechaContactoQS;
                oContacto.Email = planesVMODEL.EmailQS;
                oContacto.Tipo = 11;
                var respuestaLB = _ContactoData.LeadBrokerQC(oContacto);

                if (respuestaLB)
                {
                    var url = "http://bitrix-rummet.com:8080/api/bitrix/broker";
                    var client = new RestClient(url);
                    var request = new RestRequest(url, Method.Post);
                    request.AddHeader("Content-Type", "application/json");
                    var body = new
                    {
                        nombre = oContacto.Nombre,
                        apellidoPaterno = oContacto.APaterno,
                        apellidoMaterno = oContacto.AMaterno,
                        telefono = oContacto.Telefono,
                        correo = oContacto.Email,
                        fechaEntrega=oContacto.FechaContacto,
                        mensaje = oContacto.Mensaje,
                        //tipo = 1,
                        //productoId = 110
                    };
                    var bodyy = JsonConvert.SerializeObject(body);
                    request.AddBody(bodyy, "application/json");
                    RestResponse response = await client.ExecuteAsync(request);
                    var output = response.Content;
                    Console.WriteLine(response.Content);

                    if (response.IsSuccessful)
                    {
                        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                        var data = System.Text.Json.JsonSerializer.Deserialize<BitrixLIModel>(response.Content, options);

                        //Obtener ID de LEAD ingresado
                        var leadIB = _IntegracionData.IDLeadB(oContacto);

                        if (leadIB != 0)
                        {
                            data.IDRummet = leadIB;
                        }
                        else
                        {
                            data.IDRummet = 0;
                        }

                        data.Accion = "Quiero saber más - Exitoso";
                        data.Proveedor = "Bitrix";
                        data.Tipo = 11;
                        var integracionEntrada = _IntegracionData.IntegracionEntrada(data);
                        TempData["mssg"] = "Nos pondremos en contacto contigo en la fecha y hora acordado.";

                        TempData["mssg"] = "Nos pondremos en contacto contigo en la fecha y hora acordado.";
                        return RedirectToAction("PlanesEcommerce", "Ecommerce");

                    }
                    else
                    {
                        Console.WriteLine($"Error al hacer la solicitud: {response.ErrorMessage}");
                    }

                   
                }
                else
                {
                    TempData["mssgE"] = "Por favor válida que todos los campos estén correctamente llenados.";
                    return RedirectToAction("PlanesEcommerce", "Ecommerce");
                }

            }
            else
            {

                Console.WriteLine("Hola está mal");
            }


            return RedirectToAction("PlanesEcommerce", "Ecommerce");
        }


        [HttpPost]

        //Registro de LEAD-BROkER a través del botón de planes 
        public async Task<IActionResult> RegistroLBC(PlanesModel planesVMODEL)
        {
            if (planesVMODEL.NombreQS != null)
            {
                var oContacto = new ContactoModel();
                //Concato cuando es LB
                oContacto.Nombre = planesVMODEL.NombreQS;
                oContacto.APaterno = planesVMODEL.APaternoQS;
                oContacto.AMaterno = planesVMODEL.AMaternoQS;
                oContacto.Telefono = planesVMODEL.TelefonoQS;
                oContacto.Email = planesVMODEL.EmailQS;
                oContacto.Tipo = 22;
                var respuestaLB = _ContactoData.LeadBrokerQC(oContacto);

                if (respuestaLB)
                {
                    //Envío a Bitrix
                    var url = "http://bitrix-rummet.com:8080/api/bitrix/broker";
                    var client = new RestClient(url);
                    var request = new RestRequest(url, Method.Post);
                    request.AddHeader("Content-Type", "application/json");
                    var body = new
                    {
                        nombre = oContacto.Nombre,
                        apellidoPaterno = oContacto.APaterno,
                        apellidoMaterno = oContacto.AMaterno,
                        telefono = oContacto.Telefono,
                        correo = oContacto.Email,
                        //fechaHora=oMasInformacion.FechaMI
                        //tipo = 1,
                        //productoId = 110
                    };
                    var bodyy = JsonConvert.SerializeObject(body);
                    request.AddBody(bodyy, "application/json");
                    RestResponse response = await client.ExecuteAsync(request);
                    var output = response.Content;
                    Console.WriteLine(response.Content);

                    if (response.IsSuccessful)
                    {
                        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
                        var data = System.Text.Json.JsonSerializer.Deserialize<BitrixLIModel>(response.Content, options);

                        //Obtener ID de LEAD ingresado
                        var leadIB = _IntegracionData.IDLeadB(oContacto);

                        if (leadIB != 0)
                        {
                            data.IDRummet = leadIB;
                        }
                        else
                        {
                            data.IDRummet = 0;
                        }

                        data.Accion = "Contratar - Exitoso";
                        data.Proveedor = "Bitrix";
                        data.Tipo = 22;
                        var integracionEntrada = _IntegracionData.IntegracionEntrada(data);

                        TempData["mssg"] = "Nos pondremos en contacto contigo en la fecha y hora acordado.";
                        return RedirectToAction("PlanesEcommerce", "Ecommerce");

                    }
                    else
                    {
                        Console.WriteLine($"Error al hacer la solicitud: {response.ErrorMessage}");
                    }
                }
                else
                {
                    TempData["mssgE"] = "Por favor válida que todos los campos estén correctamente llenados.";
                    return RedirectToAction("PlanesEcommerce", "Ecommerce");
                }

            }
            else
            {

                Console.WriteLine("Hola está mal");
            }


            return RedirectToAction("PlanesEcommerce", "Ecommerce");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //Registro de LEAD-BROkER a través del botón de planes 
        public async Task<IActionResult> RegistroLeadBroker(PlanesModel planesVMODEL, string? returnurl = null)
        {
            //Comprobación de variable para verificar si el usuario viene vacío

            Console.WriteLine("Está vacía");


            /********************** CODIGO PARA LA GENERACIÓN DIRECTA DE USUARIO **********************/

EcommerceRealCVO/Views/Cuentas/Acceso.cshtml
@model AccesoVModel;
@{
    Layout = null;
 }
 
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/StyleLogin.css">
    <link rel="stylesheet" href="~/css/styless.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de sesión</title>
</head>

<body>
    <br>
    <br>
    <br>
    
    <div class="container main_backg my-4" >
        <div class="row">
            <div class="col">
                <div class="text-center text-light ">
                    <br>
                    <br>
                    
                <h4 class="fw-bold text-center text-light mb-4 mt-4">Iniciar sesión</h4>
            </div>
             <!--Aqui Inicia el Formulario-->
            
             <form asp-controller="Cuentas" asp-action="Acceso" method="post" role="form" asp-route-returnurl="@ViewData["ReturnUrl"]">
                <div class="mb-3">
                  <input asp-for="Email" type="email" class="form-control border_radius  mx-auto" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Correo electrónico">
                </div>
                <div class="mb-3">
                  <input asp-for="Password" type="password" class="form-control border_radius  mx-auto" id="exampleInputPassword1" placeholder="Contraseña">
                  
                </div>
                <div class="mb-3 text-light d-inline-block w-100 text-center" >
                    <a asp-action="OlvidoPassword" class=" modal-a">¿Olvidaste tu contraseña?</a>
                
                </div>
                
                <div class="d-grid">
                    <a type="button" class="modal-a mx-auto" data-bs-toggle="modal"
                        data-bs-target="#exampleModal">
                        
                        <h6>Aviso de privacidad</h6>
                    </a>
                    
                    <br>
                    <button type="submit" class="btn btn-light text-primary mb-3 btnn col-lg-4 mx-auto"><h6 class="my-auto fw-bold ">Iniciar sesión</h6></button>
                </div>
                <br>
                
                <div class="">
                    <!-- Button trigger modal -->
                   <br>
                   <br>
                   <br>
                   <br>

                   <!-- Modal -->
                   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                       aria-hidden="true">
                       <div class="modal-dialog">
                           <div class="modal-content">
                               <div class="modal-header">
                                   <h5 class="modal-title text-light"  id="exampleModalLabel">Aviso de privacidad</h5>
                                   <button type="button" class="btn-close " data-bs-dismiss="modal"
                                       aria-label="Close"></button>
                               </div>
                               <div class="modal-body">
                                   Lorem, ipsum dolor sit amet consectetur adipisicing elit. Totam blanditiis magni earum excepturi in optio dolor, ab rerum corporis quis ipsam! Repellat non tenetur perspiciatis quasi iste, minima aut doloribus.
                               </div>
                               <div class="modal-footer">
                                   <button type="button" class="btn btn-secondary btnn"
                                       data-bs-dismiss="modal">Aceptar</button>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>

              </form>
            </div>
            
            <div class="col bg d-none d-lg-block col-md-5 col-lg-5 col-xl d-flex">
                
               


            </div>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

   <!--  <script src="./node_modules/bootstrap/dist/js/bootstrap.min.js"></script> -->
</body>

</html>

EcommerceRealCVO/Views/Cuentas/AlertaProvisional.cshtml
@{
    Layout = "_EcommerceI";
    ViewData["Title"] = "Home Page";
}
<br />
<br />
<p>

</p>
<p>

</p>
<p></p>
<p></p>
<h2>¡Hola bienvenido!, estás a un gran paso de formar parte de nuestro equipo.</h2>
<p>Hemos enviado un correo electrónico con los pasos a seguir para continuar con tu registro. </p>
<br />
<p> Te invitamos a seguir en nuestra página</p> <a asp-controller="Home" asp-action="Index">ECOMMERCE</a>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    var strValue = "@((string)ViewBag.mssg)";

    if (strValue !== null && strValue !== "") {

        if (strValue == "Error") {
            Swal.fire(
                'Error',
                'El correo introducido ha sido registrado previamente',
                'warning'
            )

        } else {

            Swal.fire(
                'Registro exitoso',
                strValue,
                'success'
            )
        }


    }

</script>

EcommerceRealCVO/Views/Cuentas/ConfirmacionOlvidoPassword.cshtml
<h2>Confirmación de contraseña</h2>
<p>Por favor, válide su correo electrónico</p>

EcommerceRealCVO/Views/Cuentas/ConfirmacionRecuperaPassword.cshtml
<h2>Confirmación de recuperación de contraseña</h2>
<p>Su contraseña ha sido cambiada, por favor inicie sesión <a asp-controller="Cuentas" asp-action="Acceso">Acceso</a></p>

EcommerceRealCVO/Views/Cuentas/ConfirmarEmail.cshtml
<h2>¡Hola bienvenido!, gracias por querer formar parte de esta tripulación</h2>
<p>Ahora que tu email ha sido confirmado puedes iniciar sesión. Adelante -> <a asp-controller="Cuentas" asp-action="Acceso">Acceso</a></p>

EcommerceRealCVO/Views/Cuentas/Error_codigo.cshtml
<h2 class="bg-danger text-white"> Error</h2>
<p>Disculpe las molestias, algo salió mal</p>

EcommerceRealCVO/Views/Cuentas/OlvidoPassword.cshtml
@model OlvidoPasswordVModel;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Olvido de contraseña";
 }
 <title>Olvido de contraseña</title>
 <h1>Olvido de contraseña</h1>
 <form asp-controller="Cuentas" asp-action="OlvidoPassword" method="post" role="form">
     <div class="text-danger" asp-validation-summary="All"></div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input asp-for="Email" type="email"  class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

EcommerceRealCVO/Views/Cuentas/Registro.cshtml
@model RegistroVModel

@{
    ViewData["Title"] = "Resgistro de usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Registro de usuario</h1>
<form asp-controller="Cuentas" asp-action="Registro" method="post" role="form" >
    <div class="text-danger" asp-validation-summary="All"></div>

    <div class="mb-3">
        <label class="form-label">Nombre</label>
        <input asp-for="Nombre" type="text" class="form-control">
        <span asp-validation-for="Nombre" class="text-danger"></span>
      </div>

       <div class="mb-3">
        <label class="form-label">Correo</label>
        <input asp-for="Email" type="text" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label class="form-label">Telefono</label>
        <input asp-for="Telefono" type="text" class="form-control">
        <span asp-validation-for="Telefono" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label class="form-label">País</label>
        <input asp-for="Pais" type="text" class="form-control">
        <span asp-validation-for="Pais" class="text-danger"></span>
      </div>

       <div class="mb-3">
        <label class="form-label">Fecha de Nacimiento</label>
        <input type="text" name="FechaNacimiento" class="form-control" id="datepicker" placeholder="Ejemplo: 2022-10-18">
        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
      </div>

       <div class="mb-3">
        <label class="form-label">Contraseña</label>
        <input asp-for="Password"  class="form-control">
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label class="form-label">Confirma contraseña</label>
        <input asp-for="ConfirmPassword" class="form-control">
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Guardar</button>
</form>

@section Scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}}

EcommerceRealCVO/Views/Cuentas/ResetPassword.cshtml
@model RecuperaPasswordVModel

@{
    ViewData["Title"] = "Recupera contraseña";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Recupera tu contraseña</h1>
<form asp-controller="Cuentas" asp-action="ResetPassword" method="post" role="form" >
    <div class="text-danger" asp-validation-summary="All"></div>
    <!--Recuperación de contraseña TOKEN-->

    <input type="hidden" asp-for="Code" />

    <!--Prueba del ID de Usuario-->
    <input type="hidden" asp-for="UserId" />
      
    <!--

      <div class="mb-3">
        <label class="form-label">Correo</label>
        <input asp-for="Email" type="text" class="form-control">
        <span asp-validation-for="Email" class="text-danger"></span>
      </div>

    -->

       <div class="mb-3">
        <label class="form-label">Contraseña</label>
        <input asp-for="Password"  class="form-control">
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>

      <div class="mb-3">
        <label class="form-label">Confirma contraseña</label>
        <input type="password" asp-for="ConfirmPassword" class="form-control">
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
      </div>
      
      <button type="submit" class="btn btn-primary">Cambio de contraseña </button>
</form>

@section Scripts{
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}}